services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=ashraf 
      - POSTGRES_DB=nyc_taxi 
    volumes:
      - "./postgres_data:/var/lib/postgressql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
       - PGADMIN_DEFAULT_EMAIL=ashraf@admin.com
       - PGADMIN_DEFAULT_PASSWORD=ashraf
    ports:
       - "8080:80"

  # python_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - pgdatabase
  #   volumes:
  #     - "./app:/app"  # Assuming your Dockerfile is in the root of your project
